{% set name = "argon2-cffi" %}
{% set version = "19.2.0" %}
{% set sha256 = "ffaa623eea77b497ffbdd1a51e941b33d3bf552c60f14dbee274c4070677bda3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script:
    - ln -sf $RANLIB $BUILD_PREFIX/bin/ranlib  # [unix]
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler("c") }}

  host:
    - python
    - pip
    - setuptools
    - six
    - cffi >=1.0.0
    - enum34  # [py27]

  run:
    - python
    - six
    - cffi >=1.0.0
    - enum34  # [py27]

test:
  imports:
    - argon2

about:
  home: https://argon2-cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The secure Argon2 password hashing algorithm.'
  description: |
    Argon2 won the Password Hashing Competition and argon2_cffi is the simplest
    way to use it in Python and PyPy
  doc_url: https://argon2-cffi.readthedocs.io/en/stable/
  dev_url: https://github.com/hynek/argon2_cffi/

extra:
  recipe-maintainers:
    - stuertz
